const items = [
  { question: `What is Kadena's multi-chain architecture and why does it matter?`, answer: `Kadena uses a unique blockchain design called "Chainweb" with 20 parallel chains (Chain 0 through Chain 19) that work together as one network. Unlike most blockchains with a single chain, Kadena splits its operations across multiple chains for better scalability and throughput.` },
  { question: `Which Kadena chain should I use?`, answer: `Chain 0 is recommended as the default for most users.` },
  { question: `How do I know which Kadena chain my KDA is on?`, answer: `There are three ways to check which chain holds your KDA:` },
  { question: `What does "ERR_BAD_REQUEST" mean when sending KDA?`, answer: `ERR_BAD_REQUEST means ZelCore or the Kadena network rejected your transaction because something is wrong with the transaction details.` },
  { question: `How do I send KDA to an exchange?`, answer: `Exchanges are strict about which Kadena chain they accept. Sending to the wrong chain may result in lost deposits or delayed support tickets.` },
  { question: `How do I move KDA between different chains (cross-chain transfer)?`, answer: `Moving KDA between Kadena chains (e.g., from Chain 1 to Chain 0) requires a special transaction called a "cross-chain transfer."` },
  { question: `What is a "legacy address" in Kadena and why does it matter?`, answer: `A "legacy address" refers to older Kadena address formats that may not be clearly associated with a specific chain. These can cause confusion and compatibility issues.` },
  { question: `Can I use EckoWallet with ZelCore for Kadena?`, answer: `Yes! EckoWallet and ZelCore can be used together or as alternatives for managing Kadena (KDA). Each has different strengths.` },
  { question: `Why isn't my KDA showing in ZelCore even though I see it on the blockchain explorer?`, answer: `If the Kadena block explorer shows your KDA balance but ZelCore doesn't, this is a display/sync issue, not a loss of funds.` },
  { question: `What should I know about the Kadena Community Fork migration?`, answer: `The Kadena Community Fork refers to protocol updates and community-led improvements to the Kadena network. If you're using a current version of ZelCore, you likely don't need to worry about this.` },
  { question: `I sent KDA to an exchange but they say they didn't receive it. What do I do?`, answer: `If an exchange says they didn't receive your KDA deposit, the most common cause is sending to the wrong Kadena chain.` },
  { question: `How can I avoid Kadena chain-related problems?`, answer: `Most Kadena issues in ZelCore come from chain confusion or mismatches. Follow these best practices to avoid problems:` },
  { question: `I'm getting "not enough spendable" error when trying to send Monero, but I have a balance. Why?`, answer: `The "not enough spendable" error with Monero (XMR) occurs when your displayed balance includes funds that aren't yet available to spend. This is unique to Monero's privacy features and confirmation requirements.` },
  { question: `My Monero transaction failed with "Error 500" or broadcast error. What should I do?`, answer: `"Error 500" or broadcast errors when sending Monero typically indicate that ZelCore's Monero node couldn't process or broadcast your transaction to the network. This is usually temporary and has several solutions.` },
  { question: `My incoming Monero transaction isn't showing in ZelCore, but the sender says it's confirmed. What should I do?`, answer: `If someone sent you Monero (XMR) and you can verify the transaction on blockchain explorers but it's not showing in ZelCore, this is a wallet sync issue that can usually be fixed.` },
  { question: `What is Monero "rescan" and when do I need to do it?`, answer: `A Monero "rescan" forces your wallet to re-examine the blockchain from a specific point to find all transactions belonging to you. Due to Monero's privacy features, this is sometimes necessary to ensure your wallet displays the correct balance and transaction history.` },
  { question: `How do I export my Monero private keys from ZelCore to use in another wallet?`, answer: `Exporting your Monero private keys from ZelCore allows you to access your XMR in the official Monero wallet or other Monero-compatible wallets. This is useful for rescanning, verifying balance, or using advanced features.` },
  { question: `My Solana transactions are failing with "blockhash not found" or similar errors. What's wrong?`, answer: `Solana transaction failures, especially after network upgrades or during periods of network congestion, are often caused by the blockchain's unique architecture and ZelCore's interaction with Solana RPC nodes.` },
];

export default items;
