site_name: Zelcore Knowledgebase
site_url: https://docs.zelcore.io
site_author: Zelcore Technologies Inc.
site_description: >-
  Multi-asset cryptocurrency wallet for Windows, MacOS, Linux, iOS & Android.
  Store BTC, ETH, LTC, BSC/BNB & 60+ other mainnet & token chains

# Github repository
repo_name: trial123Zel/zelcore-docs
repo_url: https://github.com/trial123Zel/zelcore-docs

# Copywrite information for footer
copyright: Copyright &copy; 2023 <a href="https://zelcore.io"  target="_blank" rel="noopener">Zelcore Technologies Inc</a>
theme:
  name: material
  font:
    text: Montserrat
    code: Montserrat-LightItalic
  logo: assets/branding/LogoTextDarkBG.png
  favicon: assets/branding/favicon.png
  features:
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
  language: en
  palette:
      # palette toggle for automatic mode via OS
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    
      # palette toggle for light mode, reads user's OS default
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
      primary: blue grey
      accent: black 

      # palette toggle for dark mode, reads user's OS default
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: blue grey
      accent: black

nav:
  - Home: index.md
  - FAQ: FAQ.md
  - Supported Assets: supported_assets.md
  - Guides:
    - 'Hardware Wallets': guides/hw_wallets.md
    - 'Create an account': guides/create_account.md
    - 'Set up extra security': guides/security_setup.md
    - 'Trade Crypto': guides/quickswap.md
    - 'Buy Crypto': guides/fiat_on.md

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ZelCore-io/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zelcore_io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/zelcore-technologies-inc
  analytics:
    provider: google
    property: G-xxx
    feedback:
      title: Was this helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: unhelpful
          data: 0
          note: >-
            Thanks for your feedback!

markdown_extensions:
#  - pymdownx.highlight:
#      anchor_linenums: true
#  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
#  - pymdownx.arithmatex:
#      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg